### ISSUE TITLE
Additional changes

### ISSUE THREAD

**Issue by oAGoulart** [oAGoulart/yasl#18]
### TODO
- [ ] Move `YASL::IsFileExtSupported_` to **Script** module
- [ ] Rewrite `ConfigFile` parsing technique
- [ ] Finish **Status** module crash dump generation
- [ ] Add documentation to new function and object members
